apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baseball.fullname" . }}
  labels:
    {{- include "baseball.labels" . | nindent 4 }}
immutable: false
data:
  NUM_WORKERS: "5"
  config.ini: |-
      [DEFAULT]
      # local, api, registry
      model_source = registry

      [Database]
      db_connection_string = postgresql://baseball_app:baseball123@db:5432/baseball_db

      [ModelRegistry]
      url = https://my-model-registry-rest.apps.ocpprod.home.glroland.com
      token = none
      name = Baseball Author
      kubeconfig = kube/config

      [PredictPitch]
      dir = ./predict_play/
      # name = pitch
      # url = https://pitch.baseball.svc.cluster.local
      name = Baseball Predict Pitch
      namespace = baseball

      [PredictPlay]
      dir =  ./predict_play/
      # name = play
      # url = https://play.baseball.svc.cluster.local
      name = Baseball Predict Play
      namespace = baseball
