apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"app"}]'
  labels:
    app: predict-svc
    app.kubernetes.io/component: predict-svc
    app.kubernetes.io/instance: predict-svc
    app.kubernetes.io/name: predict-svc
    app.kubernetes.io/part-of: baseball
  name: {{ include "baseball.fullname" . }}
spec:
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "baseball.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
