apiVersion: v1
kind: Service
metadata:
  name: {{ include "baseball.fullname" . }}
  labels:
    {{- include "baseball.labels" . | nindent 4 }}
spec:
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
  internalTrafficPolicy: Cluster
  type: {{ .Values.service.type }}
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: "{{ include "baseball.fullname" . }}"
    deployment: "{{ include "baseball.fullname" . }}"
