#
# Generated by Elyra 4.2.0
#
import kfp
from kubernetes.client import *
from kubernetes.client.models import *
from kfp.kubernetes import secret, volume

from typing import Optional

# ------------------------------------------------------------------
# kfp-kubernetes 1.1.0 is misisng these function, explicity using them,
# TODO: remove these function once a new release of kfp-kubernetes is made.
# ------------------------------------------------------------------

from google.protobuf import json_format
from kfp.dsl import PipelineTask
from kfp.kubernetes import common
from kfp.kubernetes import kubernetes_executor_config_pb2 as pb

from kfp.kubernetes import add_toleration, add_pod_label, add_pod_annotation


component_def_ec4165e2076bf8c55386a507df41a6967465931ff0f44fff17797da27cc7309d = """
name: Run a file
description: Run a Jupyter notebook or Python/R script

implementation:
  container:
    image: registry.home.glroland.com/paas/ai-runtime-3.11:20250130-104034
    command: [sh, -c]
    args:
    - |
      sh -c "mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir"
      sh -c "[[ -e '/opt/app-root/bin/utils/bootstrapper.py' ]] && (echo 'bootstrapper.py file already exists'; cp '/opt/app-root/bin/utils/bootstrapper.py' .) || (echo 'Downloading https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py'; curl --fail -H 'Cache-Control: no-cache' -L 'https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py' --output bootstrapper.py)"
      sh -c "[[ -e '/opt/app-root/bin/utils/requirements-elyra.txt' ]] && (echo 'requirements-elyra.txt file already exists'; cp '/opt/app-root/bin/utils/requirements-elyra.txt' .) || (echo 'Downloading https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt'; curl --fail -H 'Cache-Control: no-cache' -L 'https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt' --output requirements-elyra.txt)"
      sh -c "python3 -m pip install  packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'Train and Deploy Models' --cos-endpoint 'https://eclipse.home.glroland.com:9000' --cos-bucket 'baseball' --cos-directory 'Train and Deploy Models-0130163949' --cos-dependencies-archive 'train_predict_pitch_model-433f9291-a22f-4e81-a347-d18a0def5d77.tar.gz' --file 'baseball/data/src/train/train_predict_pitch_model.ipynb' --outputs 'target/pitch' "
"""

factory_ec4165e2076bf8c55386a507df41a6967465931ff0f44fff17797da27cc7309d = (
    kfp.components.load_component_from_text(
        component_def_ec4165e2076bf8c55386a507df41a6967465931ff0f44fff17797da27cc7309d
    )
)

component_def_91248f55dfbc2d076e1d1523af41dd84bc6b69666abb6a0f354c8d05ca3ba7fe = """
name: Run a file
description: Run a Jupyter notebook or Python/R script

implementation:
  container:
    image: registry.home.glroland.com/paas/ai-runtime-3.11:20250130-104034
    command: [sh, -c]
    args:
    - |
      sh -c "mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir"
      sh -c "[[ -e '/opt/app-root/bin/utils/bootstrapper.py' ]] && (echo 'bootstrapper.py file already exists'; cp '/opt/app-root/bin/utils/bootstrapper.py' .) || (echo 'Downloading https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py'; curl --fail -H 'Cache-Control: no-cache' -L 'https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py' --output bootstrapper.py)"
      sh -c "[[ -e '/opt/app-root/bin/utils/requirements-elyra.txt' ]] && (echo 'requirements-elyra.txt file already exists'; cp '/opt/app-root/bin/utils/requirements-elyra.txt' .) || (echo 'Downloading https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt'; curl --fail -H 'Cache-Control: no-cache' -L 'https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt' --output requirements-elyra.txt)"
      sh -c "python3 -m pip install  packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'Train and Deploy Models' --cos-endpoint 'https://eclipse.home.glroland.com:9000' --cos-bucket 'baseball' --cos-directory 'Train and Deploy Models-0130163949' --cos-dependencies-archive 'train_predict_play_model-f180850c-0736-4cf0-9532-636100845feb.tar.gz' --file 'baseball/data/src/train/train_predict_play_model.ipynb' --outputs 'target/play' "
"""

factory_91248f55dfbc2d076e1d1523af41dd84bc6b69666abb6a0f354c8d05ca3ba7fe = (
    kfp.components.load_component_from_text(
        component_def_91248f55dfbc2d076e1d1523af41dd84bc6b69666abb6a0f354c8d05ca3ba7fe
    )
)

component_def_ab960bd6aba0ad40ee25915f2d4629d3e5addc3a4ab48e7d20efd17a6dd869e0 = """
name: Run a file
description: Run a Jupyter notebook or Python/R script

implementation:
  container:
    image: registry.home.glroland.com/paas/ai-runtime-3.11:20250130-104034
    command: [sh, -c]
    args:
    - |
      sh -c "mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir"
      sh -c "[[ -e '/opt/app-root/bin/utils/bootstrapper.py' ]] && (echo 'bootstrapper.py file already exists'; cp '/opt/app-root/bin/utils/bootstrapper.py' .) || (echo 'Downloading https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py'; curl --fail -H 'Cache-Control: no-cache' -L 'https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py' --output bootstrapper.py)"
      sh -c "[[ -e '/opt/app-root/bin/utils/requirements-elyra.txt' ]] && (echo 'requirements-elyra.txt file already exists'; cp '/opt/app-root/bin/utils/requirements-elyra.txt' .) || (echo 'Downloading https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt'; curl --fail -H 'Cache-Control: no-cache' -L 'https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt' --output requirements-elyra.txt)"
      sh -c "python3 -m pip install  packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'Train and Deploy Models' --cos-endpoint 'https://eclipse.home.glroland.com:9000' --cos-bucket 'baseball' --cos-directory 'Train and Deploy Models-0130163949' --cos-dependencies-archive 'store_assets-58acfdbe-7e0c-4d7e-acc0-88d0c0789879.tar.gz' --file 'baseball/data/src/train/store_assets.py' --inputs 'target/play;target/pitch' "
"""

factory_ab960bd6aba0ad40ee25915f2d4629d3e5addc3a4ab48e7d20efd17a6dd869e0 = (
    kfp.components.load_component_from_text(
        component_def_ab960bd6aba0ad40ee25915f2d4629d3e5addc3a4ab48e7d20efd17a6dd869e0
    )
)

component_def_7f739c7dab20dcc44370aab10340bcd0284b982d8bf8044bb4b5c73bedbd7921 = """
name: Run a file
description: Run a Jupyter notebook or Python/R script

implementation:
  container:
    image: registry.home.glroland.com/paas/ai-runtime-3.11:20250130-104034
    command: [sh, -c]
    args:
    - |
      sh -c "mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir"
      sh -c "[[ -e '/opt/app-root/bin/utils/bootstrapper.py' ]] && (echo 'bootstrapper.py file already exists'; cp '/opt/app-root/bin/utils/bootstrapper.py' .) || (echo 'Downloading https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py'; curl --fail -H 'Cache-Control: no-cache' -L 'https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py' --output bootstrapper.py)"
      sh -c "[[ -e '/opt/app-root/bin/utils/requirements-elyra.txt' ]] && (echo 'requirements-elyra.txt file already exists'; cp '/opt/app-root/bin/utils/requirements-elyra.txt' .) || (echo 'Downloading https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt'; curl --fail -H 'Cache-Control: no-cache' -L 'https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt' --output requirements-elyra.txt)"
      sh -c "python3 -m pip install  packaging && python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py --pipeline-name 'Train and Deploy Models' --cos-endpoint 'https://eclipse.home.glroland.com:9000' --cos-bucket 'baseball' --cos-directory 'Train and Deploy Models-0130163949' --cos-dependencies-archive 'register_models-21dd30bf-689c-4732-83b1-30452017f236.tar.gz' --file 'baseball/data/src/train/register_models.py' --inputs 'target/play;target/pitch' "
"""

factory_7f739c7dab20dcc44370aab10340bcd0284b982d8bf8044bb4b5c73bedbd7921 = (
    kfp.components.load_component_from_text(
        component_def_7f739c7dab20dcc44370aab10340bcd0284b982d8bf8044bb4b5c73bedbd7921
    )
)


@kfp.dsl.pipeline(name="Train and Deploy Models")
def generated_pipeline():

    # Task for node 'train-pitch-model'
    task_433f9291_a22f_4e81_a347_d18a0def5d77 = (
        factory_ec4165e2076bf8c55386a507df41a6967465931ff0f44fff17797da27cc7309d()
    )

    secret.use_secret_as_env(
        task_433f9291_a22f_4e81_a347_d18a0def5d77,
        "dashboard-dspa-secret",
        {
            "AWS_ACCESS_KEY_ID": "AWS_ACCESS_KEY_ID",
            "AWS_SECRET_ACCESS_KEY": "AWS_SECRET_ACCESS_KEY",
        },
    )

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_display_name("train-pitch-model")

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_cpu_request(cpu="6")

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_memory_request(memory="2G")

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_cpu_limit(cpu="6")

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_memory_limit(memory="2G")

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_env_variable(
        name="OUTPUT_DIR", value="target/pitch"
    )

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_env_variable(
        name="DB_CONNECTION_STRING",
        value="postgresql://baseball_app:baseball123@db/baseball_db",
    )

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_env_variable(
        name="DATASET_SIZE", value="5000"
    )

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_env_variable(
        name="ELYRA_RUNTIME_ENV", value="kfp"
    )

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_env_variable(
        name="ELYRA_ENABLE_PIPELINE_INFO", value="True"
    )

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_env_variable(
        name="ELYRA_WRITABLE_CONTAINER_DIR", value="/tmp"
    )

    task_433f9291_a22f_4e81_a347_d18a0def5d77.set_env_variable(
        name="ELYRA_RUN_NAME", value="{{workflow.uid}}"
    )

    add_pod_label(
        task_433f9291_a22f_4e81_a347_d18a0def5d77, "elyra/node-type", "notebook-script"
    )

    add_pod_label(
        task_433f9291_a22f_4e81_a347_d18a0def5d77,
        "elyra/pipeline-name",
        "Train_and_Deploy_Models",
    )

    add_pod_label(
        task_433f9291_a22f_4e81_a347_d18a0def5d77, "elyra/pipeline-version", ""
    )

    add_pod_label(
        task_433f9291_a22f_4e81_a347_d18a0def5d77, "elyra/experiment-name", ""
    )

    add_pod_label(
        task_433f9291_a22f_4e81_a347_d18a0def5d77,
        "elyra/node-name",
        "train-pitch-model",
    )

    add_pod_annotation(
        task_433f9291_a22f_4e81_a347_d18a0def5d77,
        "elyra/node-file-name",
        """baseball/data/src/train/train_predict_pitch_model.ipynb""",
    )

    add_pod_annotation(
        task_433f9291_a22f_4e81_a347_d18a0def5d77,
        "elyra/pipeline-source",
        """Train and Deploy Models.pipeline""",
    )

    # Task for node 'train-play-model'
    task_f180850c_0736_4cf0_9532_636100845feb = (
        factory_91248f55dfbc2d076e1d1523af41dd84bc6b69666abb6a0f354c8d05ca3ba7fe()
    )

    secret.use_secret_as_env(
        task_f180850c_0736_4cf0_9532_636100845feb,
        "dashboard-dspa-secret",
        {
            "AWS_ACCESS_KEY_ID": "AWS_ACCESS_KEY_ID",
            "AWS_SECRET_ACCESS_KEY": "AWS_SECRET_ACCESS_KEY",
        },
    )

    task_f180850c_0736_4cf0_9532_636100845feb.set_display_name("train-play-model")

    task_f180850c_0736_4cf0_9532_636100845feb.set_cpu_request(cpu="6")

    task_f180850c_0736_4cf0_9532_636100845feb.set_memory_request(memory="2G")

    task_f180850c_0736_4cf0_9532_636100845feb.set_cpu_limit(cpu="6")

    task_f180850c_0736_4cf0_9532_636100845feb.set_memory_limit(memory="2G")

    task_f180850c_0736_4cf0_9532_636100845feb.set_env_variable(
        name="OUTPUT_DIR", value="target/play"
    )

    task_f180850c_0736_4cf0_9532_636100845feb.set_env_variable(
        name="DB_CONNECTION_STRING",
        value="postgresql://baseball_app:baseball123@db/baseball_db",
    )

    task_f180850c_0736_4cf0_9532_636100845feb.set_env_variable(
        name="DATASET_SIZE", value="5000"
    )

    task_f180850c_0736_4cf0_9532_636100845feb.set_env_variable(
        name="ELYRA_RUNTIME_ENV", value="kfp"
    )

    task_f180850c_0736_4cf0_9532_636100845feb.set_env_variable(
        name="ELYRA_ENABLE_PIPELINE_INFO", value="True"
    )

    task_f180850c_0736_4cf0_9532_636100845feb.set_env_variable(
        name="ELYRA_WRITABLE_CONTAINER_DIR", value="/tmp"
    )

    task_f180850c_0736_4cf0_9532_636100845feb.set_env_variable(
        name="ELYRA_RUN_NAME", value="{{workflow.uid}}"
    )

    add_pod_label(
        task_f180850c_0736_4cf0_9532_636100845feb, "elyra/node-type", "notebook-script"
    )

    add_pod_label(
        task_f180850c_0736_4cf0_9532_636100845feb,
        "elyra/pipeline-name",
        "Train_and_Deploy_Models",
    )

    add_pod_label(
        task_f180850c_0736_4cf0_9532_636100845feb, "elyra/pipeline-version", ""
    )

    add_pod_label(
        task_f180850c_0736_4cf0_9532_636100845feb, "elyra/experiment-name", ""
    )

    add_pod_label(
        task_f180850c_0736_4cf0_9532_636100845feb, "elyra/node-name", "train-play-model"
    )

    add_pod_annotation(
        task_f180850c_0736_4cf0_9532_636100845feb,
        "elyra/node-file-name",
        """baseball/data/src/train/train_predict_play_model.ipynb""",
    )

    add_pod_annotation(
        task_f180850c_0736_4cf0_9532_636100845feb,
        "elyra/pipeline-source",
        """Train and Deploy Models.pipeline""",
    )

    # Task for node 'store-assets'
    task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879 = (
        factory_ab960bd6aba0ad40ee25915f2d4629d3e5addc3a4ab48e7d20efd17a6dd869e0()
    )

    secret.use_secret_as_env(
        task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879,
        "dashboard-dspa-secret",
        {
            "AWS_ACCESS_KEY_ID": "AWS_ACCESS_KEY_ID",
            "AWS_SECRET_ACCESS_KEY": "AWS_SECRET_ACCESS_KEY",
        },
    )

    task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879.set_display_name("store-assets")

    task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879.set_env_variable(
        name="S3_REGION", value="lab"
    )

    task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879.set_env_variable(
        name="ELYRA_RUNTIME_ENV", value="kfp"
    )

    task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879.set_env_variable(
        name="ELYRA_ENABLE_PIPELINE_INFO", value="True"
    )

    task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879.set_env_variable(
        name="ELYRA_WRITABLE_CONTAINER_DIR", value="/tmp"
    )

    task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879.set_env_variable(
        name="ELYRA_RUN_NAME", value="{{workflow.uid}}"
    )

    add_pod_label(
        task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879, "elyra/node-type", "notebook-script"
    )

    add_pod_label(
        task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879,
        "elyra/pipeline-name",
        "Train_and_Deploy_Models",
    )

    add_pod_label(
        task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879, "elyra/pipeline-version", ""
    )

    add_pod_label(
        task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879, "elyra/experiment-name", ""
    )

    add_pod_label(
        task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879, "elyra/node-name", "store-assets"
    )

    add_pod_annotation(
        task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879,
        "elyra/node-file-name",
        """baseball/data/src/train/store_assets.py""",
    )

    add_pod_annotation(
        task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879,
        "elyra/pipeline-source",
        """Train and Deploy Models.pipeline""",
    )

    task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879.after(
        task_433f9291_a22f_4e81_a347_d18a0def5d77
    )

    task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879.after(
        task_f180850c_0736_4cf0_9532_636100845feb
    )

    # Task for node 'register-models'
    task_21dd30bf_689c_4732_83b1_30452017f236 = (
        factory_7f739c7dab20dcc44370aab10340bcd0284b982d8bf8044bb4b5c73bedbd7921()
    )

    secret.use_secret_as_env(
        task_21dd30bf_689c_4732_83b1_30452017f236,
        "dashboard-dspa-secret",
        {
            "AWS_ACCESS_KEY_ID": "AWS_ACCESS_KEY_ID",
            "AWS_SECRET_ACCESS_KEY": "AWS_SECRET_ACCESS_KEY",
        },
    )

    task_21dd30bf_689c_4732_83b1_30452017f236.set_display_name("register-models")

    task_21dd30bf_689c_4732_83b1_30452017f236.set_env_variable(
        name="REGISTRY_AUTHOR", value="admin"
    )

    task_21dd30bf_689c_4732_83b1_30452017f236.set_env_variable(
        name="ELYRA_RUNTIME_ENV", value="kfp"
    )

    task_21dd30bf_689c_4732_83b1_30452017f236.set_env_variable(
        name="ELYRA_ENABLE_PIPELINE_INFO", value="True"
    )

    task_21dd30bf_689c_4732_83b1_30452017f236.set_env_variable(
        name="ELYRA_WRITABLE_CONTAINER_DIR", value="/tmp"
    )

    task_21dd30bf_689c_4732_83b1_30452017f236.set_env_variable(
        name="ELYRA_RUN_NAME", value="{{workflow.uid}}"
    )

    add_pod_label(
        task_21dd30bf_689c_4732_83b1_30452017f236, "elyra/node-type", "notebook-script"
    )

    add_pod_label(
        task_21dd30bf_689c_4732_83b1_30452017f236,
        "elyra/pipeline-name",
        "Train_and_Deploy_Models",
    )

    add_pod_label(
        task_21dd30bf_689c_4732_83b1_30452017f236, "elyra/pipeline-version", ""
    )

    add_pod_label(
        task_21dd30bf_689c_4732_83b1_30452017f236, "elyra/experiment-name", ""
    )

    add_pod_label(
        task_21dd30bf_689c_4732_83b1_30452017f236, "elyra/node-name", "register-models"
    )

    add_pod_annotation(
        task_21dd30bf_689c_4732_83b1_30452017f236,
        "elyra/node-file-name",
        """baseball/data/src/train/register_models.py""",
    )

    add_pod_annotation(
        task_21dd30bf_689c_4732_83b1_30452017f236,
        "elyra/pipeline-source",
        """Train and Deploy Models.pipeline""",
    )

    task_21dd30bf_689c_4732_83b1_30452017f236.after(
        task_58acfdbe_7e0c_4d7e_acc0_88d0c0789879
    )


if __name__ == "__main__":
    from pathlib import Path

    kfp.compiler.Compiler().compile(
        pipeline_func=generated_pipeline,
        package_path=Path(__file__).with_suffix(".yaml").name,
    )
